import turtle as t
t.shape ("turtle")
t.speed(20)
t.lt(90)
t.fd(200)
t.rt(90)
n=5
t.color("yellow")
t.begin_fill()
for x in range(n):
    t.fd(50)
    t.lt(360/n)
t.end_fill()

t.fd(50)
t.right(30)
t.color("yellow")
t.begin_fill()
for x in range(n):
    t.fd(50)
    t.lt(360/n)
t.end_fill()

t.fd(50)
t.right(30)
t.color("yellow")
t.begin_fill()
for x in range(n):
    t.fd(50)
    t.lt(360/n)
t.end_fill()

t.fd(50)
t.right(30)
t.color("yellow")
t.begin_fill()
for x in range(n):
    t.fd(50)
    t.lt(360/n)
t.end_fill()
t.fd(50)
t.right(30)
t.color("yellow")
t.begin_fill()
for x in range(n):
    t.fd(50)
    t.lt(360/n)
t.end_fill()
t.fd(50)
t.right(30)
t.color("yellow")
t.begin_fill()
for x in range(n):
    t.fd(50)
    t.lt(360/n)
t.end_fill()
t.fd(50)
t.right(30)
t.color("yellow")
t.begin_fill()
for x in range(n):
    t.fd(50)
    t.lt(360/n)
t.end_fill()
t.fd(50)
t.right(30)
t.color("yellow")
t.begin_fill()
for x in range(n):
    t.fd(50)
    t.lt(360/n)
t.end_fill()
t.fd(50)
t.right(30)
t.color("yellow")
t.begin_fill()
for x in range(n):
    t.fd(50)
    t.lt(360/n)
t.end_fill()
t.fd(50)
t.right(30)
t.color("yellow")
t.begin_fill()
for x in range(n):
    t.fd(50)
    t.lt(360/n)
t.end_fill()
t.fd(50)
t.right(30)
t.color("yellow")
t.begin_fill()
for x in range(n):
    t.fd(50)
    t.lt(360/n)
t.end_fill()
t.fd(50)
t.right(30)
t.color("yellow")
t.begin_fill()
for x in range(n):
    t.fd(50)
    t.lt(360/n)
t.end_fill()
t.fd(50)
t.right(30)
t.color("yellow")
t.begin_fill()
for x in range(n):
    t.fd(50)
    t.lt(360/n)
t.end_fill()
t.right(90)
t.color("white")
t.fd(250)
t.begin_fill()
t.color("brown")
t.fd(200)
t.lt(90)
t.fd(50)
t.lt(90)
t.fd(200)
t.lt(90)
t.end_fill()
t.lt(90)
t.fd(200)
t.rt(90)
t.fd(50)
t.rt(90)
t.fd(100)
t.lt(90)
t.begin_fill()
t.color("green")
t.circle(50)
t.rt(180)
t.fd(50)
t.circle(50)
t.end_fill()
t.begin_fill()
t.color("brown")
t.lt(90)
t.fd(100)
t.lt(90)
t.fd(50)
t.lt(90)
t.fd(200)
t.lt(90)
t.fd(50)
t.lt(90)
t.fd(100)
t.end_fill()

